const stringsRU = {
	main: "Главная",
	about_sedona: "О Седоне",
	hotel: "Гостиница",
	i_want_to_go_there: "Хочу туда!",
	top_banner_title: "Седона — небольшой городок в Аризоне,\n" + "заслуживающий большего!",
	top_banner_subtitle: "Рассмотрим 5 причин, по которым Седона круче, чем Гранд-Каньон!",
	housing: "Жильё",
	food: "Еда",
	souvenir: "Сувениры",
	housing_description: "Рекомендуем пожить \n" + "в настоящем мотеле, \n" + "всё как в кино!",
	food_description: "Всегда заказывайте\n" + "топовый фирменный бургер, \n" + "вы не разочаруетесь!",
	souvenir_description: "Не только китайского, \n" + "но и настоящего местного производства!",
	small_area: "Небольшая\n" + "площадь",
	beautiful_road: "Красивая\n" + "дорога",
	few_tourists: "Мало\n" + "туристов",
	all_attractions_are_very_close: "Все достопримечательности \n" + "находятся очень близко",
	traveling_to_sedona: "Ехать в Седону из Лас-Вегаса \n" + "совсем не скучно!",
	most_go_to_grand_canyon: "Большинство едет в Гранд \n" + "Каньон и толпится там",
	real_town: "Настоящий\n" + "городок",
	sedona_is_not_a_tourist_attraction: "Седона — не аттракцион для туристов, там течёт \n" + "своя жизнь",
	there_is_devils_bridge: "Там есть\n" + "мост дьявола",
	yes_you_can_through_it: "Да, по нему можно пройти! Если вы осмелитесь, разумеется",
	interested: "Заинтересовались?",
	indicate_your_expected_travel_dates:
		"Укажите предполагаемые даты поездки,\n" + "и мы покажем вам лучшие предложения гостиниц в Седоне\n",
	search_hotel_sedona: "Поиск гостинницы в Седоне",
	subscribe_to_the_newsletter: "Подпишись на рассылку",
	only_useful_information: "Только полезная информация и никакого спама,\n" + "честное бойскаутское!",
	your_e_mail: "Ваш e-mail",
	subscribe: "Подписаться",
	myPhoneNumber: "996705550511",
	myPhoneNumberView: "+996 705 55-05-11",
};

export default stringsRU;
